import type { Metadata } from 'next'
import { IBM_Plex_Sans } from 'next/font/google'
import { PropsWithChildren } from 'react'
import { Providers } from './providers'
import './globals.css'

const ibmPlexSans = IBM_Plex_Sans({
  variable: '--font-ibm-plex-sans',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ru">
      <body className={ibmPlexSans.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
